### ISSUE TITLE
Darwin core archive ingest in R

### ISSUE THREAD

**Issue by sckott** [idigbio-api-hackathon/HackathonCentral#18]
It was mentioned during the call today that the download API provides darwin core archives. I've been working on an R client for ingesting these https://github.com/ropensci/finch  - would be good to harden this a bit and maybe import in the R client for easy open of files from the download API

**Comment by mjcollin** [comment]
The future download API will also support CSV and once the new system is done (July?) we'll get some kind of support for the download endpoint into the libraries. DwCA is much richer though and having that be the default download type and being supported in R would be great. The returned df could then match the df returned from search calls.

**Comment by sckott** [comment]
All sounds good.

**Comment by sckott** [comment]
decided not to work on this, closing
